version: 2.1
jobs:
  build-all:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download and build vecmath 
          command: |
            git clone https://github.com/rsahlin/vecmath.git
            cd vecmath
            mvn compile install
      - run:
         name: Build graphics-by-opengl No Android
         command: |
           mvn compile install -DskipTests -DAndroid=false
  

workflows:
  version: 2.1
  main:
    jobs:
      - build-all
