version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
       - image: buildpack-deps:trusty
     steps:
       - git clone ssh://github.com/rsahlin/vecmath.git
       - checkout
       - run: mvn compile

